baseurl: '/'
permalink: pretty
title: 'Caroline Academy'

logo:
  mobile: "images/logo/logo-mobile.jpg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo_2.jpg"
  desktop_height: "50px"
  desktop_width: "272px"

home: 
  limit_services: 6

collections:
  edutours:
    output: true
    sort_by: weight
  programs:
    output: true

defaults:
  - scope:
      path: ""
      type: "edutours"
    values:
      layout: "edutour"
  - scope:
      path: ""
      type: "programs"
    values:
      layout: "program"

sass:
  style: compressed # possible values: nested expanded compact compressed

collections:
  edutours:
    output: true
    sort_by: weight

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
